name: Keep Streamlit Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App (browser-like)
        run: |
          echo "Acessando app..."

          curl https://inteligenciafinanceira.streamlit.app/ \
            -L \
            --cookie-jar cookies.txt \
            --cookie cookies.txt \
            --max-redirs 10 \
            --connect-timeout 10 \
            --max-time 40 \
            --silent \
            --output /dev/null \
            --write-out "HTTP Status: %{http_code}\n"
